id: P000567
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W21860
  title: རྒྱུན་སྤྱོད་བོད་རིགས་གཏམ་དཔེ་བསགས་མཛོད
  author: ''
  volumes:
    d1429d95bd8f4f6ea7712649c8fac299:
      image_group_id: I4853
      title: ''
      volume_number: 1
      total_pages: 661
      base_file: v001.txt
